
application:
  applicationName: "customer"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        KEYCLOAK_REALM: "nordmart"
        KEYCLOAK_URL:  "https://iam-keycloak-nordmart-dev.apps.binero.06p407u4.kubeapp.cloud/auth/"
        KEYCLOAK_CLIENT_BACKEND: "stakater-nordmart-backend"
        KEYCLOAK_CLIENT_SECRET_KEY: "7672aea2-81ff-4aa2-affe-daf3bad10334"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
        CATALOG_ENDPOINT: "catalog:8080"
        CASSANDRA_HOST: "cassandra"
        CASSANDRA_USERNAME: "cassandra"
  deployment:
    envFrom:
    - type: configmap
      name: ""
    additionalLabels:
      appCategory: "backend"
    annotations:
    imagePullSecrets: nexus-docker-config-forked
    image:
      repository: stakater/stakater-nordmart-customer
      tag: v0.0.1
    volumes: {}
    env:
    - name: CASSANDRA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cassandra 
          key: cassandra-password
    resources: 
      limits:
        memory: 1Gi 
        cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1  
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
  service:
    ports:
    - port: 8080
      name: https
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  configMap:
    enabled: false
cassandra:
  fullnameOverride: cassandra
  jvm:
    maxHeapSize: 512M
    newHeapSize: 512M
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    name: cassandra
    endpointSnitch: GossipingPropertyFileSnitch
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

  
  