applicationName: "customer"
deployment:
  annotations:
  podLabels:
    app: customer
  image:
    repository: stakater/customer
    tag: v0.0.1
  volumes: {}
  env:
  - name: CATALOG_ENDPOINT
    value: "catalog.default.svc.cluster.local:8080"
  - name: CASSANDRA_HOST
    value: "cassandra.default.svc.cluster.local"
  - name: KEYCLOAK_REALM
    value: "nordmart"
  - name: KEYCLOAK_URL
    value: "https://keycloak-dev.nordmart-eks.stakater.com/auth/"
  - name: KEYCLOAK_CLIENT_BACKEND
    value: "stakater-nordmart-backend"
  - name: KEYCLOAK_CLIENT_SECRET_KEY
    value: "7672aea2-81ff-4aa2-affe-daf3bad10334"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /actuator/health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /actuator/health
        port: 8080
service:
  ports:
  - port: 8080
    name: https
    targetPort: 8080
rbac:
  create: true
  serviceAccount:
    create: true
configMap:
  enabled: false

ingress:
  enabled: false
  servicePort: 8080
  hosts:
    - chart-example.local
  annotations: 
    # kubernetes.io/ingress.class: external-ingress
    # ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/force-ssl-redirect: true
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
